version: 2
jobs:
  deploy:
    working_directory: ~/nextweb
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: บิ้วด๊อกเก้ออิมเมจ
          command: |
            docker build -t nextweb .
      - run:
          name: พุชด๊อกเก้ออิมเมจ
          command: |
            docker login -u $DOCKER_HUB_USER_ID -p $DOCKER_HUB_PASSWORD
            docker tag nextweb $DOCKER_HUB_USER_ID/nextweb:$CIRCLE_SHA1
            docker tag nextweb $DOCKER_HUB_USER_ID/nextweb:latest
            docker push $DOCKER_HUB_USER_ID/nextweb:$CIRCLE_SHA1
            docker push $DOCKER_HUB_USER_ID/nextweb:latest

      - run:
          name: Install awscli
          command: |
            npm install aws-sdk
      - run:
          name: Create AWS credentials manually
          command: |
            mkdir ~/.aws
            touch ~/.aws/config
            chmod 600 ~/.aws/config
            echo "[profile eb-cli]" > ~/.aws/config
            echo "aws_access_key_id=$AWS_ACCESS_KEY_ID" >> ~/.aws/config
            echo "aws_secret_access_key=$AWS_SECRET_ACCESS_KEY" >> ~/.aws/config
      - run:
          name: Deploy to EB if branch is Master
          command: |
             eb use server-backend-env --profile eb-cli
             eb deploy -v --staged --profile eb-cli
workflows:
  version: 2
  build-deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: 
                - master
