version: 2
jobs:
  build:
    working_directory: ~/nextweb
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout
      - setup_remote_docker
      # - run:
      #     name: Install dependencies
      #     command: |
      #       apk add --no-cache py-pip=9.0.0-r1
      #       pip install docker-compose==1.15.0
      - deploy:
          name: push Docker Image
          command: |
            docker login -u $DOCKER_HUB_USER_ID -p $DOCKER_HUB_PASSWORD
            docker tag nextweb_nextweb $DOCKER_HUB_USER_ID/nextweb:$CIRCLE_SHA1
            docker tag nextweb_nextweb $DOCKER_HUB_USER_ID/nextweb:latest
            docker push $DOCKER_HUB_USER_ID/nextweb:$CIRCLE_SHA1
            docker push $DOCKER_HUB_USER_ID/nextweb:latest